"""Add sherlock_plan field to stores

Revision ID: 9b40d94abb56
Revises: ae32cd163dad
Create Date: 2025-12-27 16:49:40.457610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b40d94abb56'
down_revision: Union[str, None] = 'ae32cd163dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('sherlock_plan', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'sherlock_plan')
    # ### end Alembic commands ###
