"""Add scan scheduling and status fields to stores

Revision ID: ae32cd163dad
Revises: add_system_settings
Create Date: 2025-12-27 14:15:15.849736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae32cd163dad'
down_revision: Union[str, None] = 'add_system_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('scan_slot', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('scan_in_progress', sa.Boolean(), nullable=True))
    op.add_column('stores', sa.Column('last_scan_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('last_scan_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stores', sa.Column('last_scan_status', sa.String(length=20), nullable=True))
    op.add_column('stores', sa.Column('last_scan_error', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('scan_failure_count', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('needs_extended_scan', sa.Boolean(), nullable=True))
    op.alter_column('stores', 'timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'timezone',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::text"))
    op.drop_column('stores', 'needs_extended_scan')
    op.drop_column('stores', 'scan_failure_count')
    op.drop_column('stores', 'last_scan_error')
    op.drop_column('stores', 'last_scan_status')
    op.drop_column('stores', 'last_scan_completed_at')
    op.drop_column('stores', 'last_scan_started_at')
    op.drop_column('stores', 'scan_in_progress')
    op.drop_column('stores', 'scan_slot')
    # ### end Alembic commands ###
